/**
 * Tasks API client.
 *
 * Thin typed wrappers over the Tier-2 task endpoints shipped in T11/T13:
 *   * `GET    /api/v1/tasks`              (list, paginated + filtered)
 *   * `GET    /api/v1/tasks/{task_id}`    (single)
 *   * `POST   /api/v1/tasks/{task_id}/cancel`
 *   * `POST   /api/v1/workflows/{wf_id}/batch` (batch submit, T10)
 *
 * Why hand-rolled types: the generated `schema.d.ts` is regenerated by
 * `pnpm codegen:api:offline`, which needs the API server up to snapshot
 * OpenAPI. The list + stream + batch endpoints landed in T10/T13 after
 * the last codegen pass, so the typed paths aren't there yet. Mirroring
 * the contract here keeps T14 unblocked; a follow-up codegen run will
 * tighten this back to `apiClient.GET(...)`-style calls.
 *
 * All requests funnel through the same `apiClient` so they pick up the
 * auth `Authorization` header + 401 handling for free.
 */
import { apiClient } from '@/lib/api/client';
import { getApiBase } from '@/lib/base-path';
import type {
  ResourceAccess,
  ResourceProvenance,
} from '@/lib/api/organizations';

// ---------------------------------------------------------------------------
// Contract — kept in sync with `routes/tasks.py::_task_to_out` and the
// `ck_tasks_status` CHECK constraint in `models_tasks.py`.
// ---------------------------------------------------------------------------

export type TaskStatus =
  | 'queued'
  | 'running'
  | 'resuming'
  | 'finished'
  | 'finished_with_errors'
  | 'failed'
  | 'interrupted'
  | 'cancelling'
  | 'cancelled'
  | 'enabled'
  | 'paused';

export type TaskType = 'batch_exec' | 'scheduled_run';

export interface Task {
  id: string;
  status: TaskStatus;
  /** Progress in [0, 1]. `0` for queued tasks, `1` for finished. */
  progress: number;
  task_type: TaskType;
  workflow_id: string | null;
  payload: unknown;
  result: unknown;
  results_uri: string | null;
  error: string | null;
  background_job_id: string | null;
  sandbox_status?: TaskSandboxStatus | null;
  submitted_at: string;
  started_at: string | null;
  finished_at: string | null;
  access: ResourceAccess;
  provenance: ResourceProvenance;
}

export type TaskSandboxStatus =
  | 'pending'
  | 'starting'
  | 'running'
  | 'releasing'
  | 'released'
  | 'lost'
  | 'failed_to_start';

export type TaskEventType = 'state' | 'progress' | 'log' | 'result' | 'terminal';

export interface TaskEventPayload {
  schema_version?: number;
  _event_ts?: string;
  level?: 'debug' | 'info' | 'warning' | 'error' | string;
  category?: string;
  action?: string;
  message?: string;
  task_status?: TaskStatus | string;
  sandbox_status?: TaskSandboxStatus | string;
  scope?: { type?: string; id?: string | null; name?: string | null } | null;
  progress?: {
    done?: number;
    total?: number;
    unit?: string;
    percent?: number;
  } | null;
  data?: unknown;
  error?: {
    code?: string;
    message?: string;
    retryable?: boolean;
    details?: unknown;
  } | null;
}

export interface TaskEvent {
  id: number;
  task_id: string;
  ts: string | null;
  event_type: TaskEventType;
  payload: TaskEventPayload;
}

export interface ListTasksParams {
  status?: TaskStatus[];
  task_type?: TaskType[];
  workflow_id?: string;
  q?: string;
  limit?: number;
  offset?: number;
}

export interface TaskListResponse {
  items: Task[];
  total: number;
  limit: number;
  offset: number;
}

export interface TaskSummary {
  active: number;
  enabled?: number;
  paused?: number;
  queued: number;
  running: number;
  resuming?: number;
  cancelling: number;
  failed: number;
  finished: number;
  finished_with_errors?: number;
  interrupted?: number;
  cancelled: number;
}

export interface TaskEventsResponse {
  items: TaskEvent[];
  limit: number;
  after_seq: number | null;
  before_seq: number | null;
  order: 'asc' | 'desc';
  next_cursor: number | null;
  latest_seq: number;
}

export type CancelMode = 'soft' | 'force';

export interface ScheduledRunConfig {
  id: string;
  task_id: string;
  workflow_id: string;
  name: string;
  enabled: boolean;
  schedule_type: 'interval' | 'cron';
  cron_expr: string | null;
  interval_seconds: number | null;
  timezone: string;
  input_preset: Record<string, unknown>;
  mount_enabled: boolean;
  notification_policy: Record<string, unknown>;
  concurrency_policy: string;
  failure_policy: string;
  catchup_policy: boolean;
  next_run_at: string | null;
  end_at: string | null;
  last_run_at: string | null;
  last_status: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface ScheduledRunExecution {
  id: string;
  schedule_id: string;
  workflow_id: string;
  run_key: string;
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled' | 'skipped';
  trigger_type: 'scheduled' | 'manual';
  triggered_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  input_snapshot: Record<string, unknown>;
  result: unknown;
  results_uri: string | null;
  error: string | null;
  run_state: Record<string, unknown>;
  notification_state: Record<string, unknown>;
}

export interface ScheduledRunResponse {
  task: Task;
  schedule: ScheduledRunConfig;
}

export interface ScheduledRunCreateBody {
  name: string;
  workflow_id: string;
  enabled?: boolean;
  schedule_type: 'interval' | 'cron';
  interval_seconds?: number | null;
  cron_expr?: string | null;
  timezone?: string;
  start_at?: string | null;
  end_at?: string | null;
  input_preset?: Record<string, unknown>;
  mount_enabled?: boolean;
  notification_policy?: Record<string, unknown>;
}

export interface ScheduledRunExecutionsResponse {
  items: ScheduledRunExecution[];
  total: number;
  limit: number;
  offset: number;
}

// ---------------------------------------------------------------------------
// Internal: thin fetch helper that reuses the same base URL + auth header
// pipeline the typed `apiClient` uses. `openapi-fetch` exposes the underlying
// `fetch` it composed via `apiClient.GET / POST` — we go one layer below for
// the un-codegenned routes so we still pick up the auth middleware.
// ---------------------------------------------------------------------------

const BASE = getApiBase();

/**
 * Mirror the `Authorization` + 401 middleware behaviour of `apiClient`
 * for paths that aren't yet in `schema.d.ts`. We import the auth store
 * lazily to avoid a circular import in tests.
 */
async function authedFetch(
  path: string,
  init: RequestInit = {},
): Promise<Response> {
  const { useAuthStore } = await import('@/stores/auth');
  const token = useAuthStore.getState().token;
  const headers = new Headers(init.headers);
  if (token) headers.set('Authorization', `Bearer ${token}`);
  if (init.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }
  const resp = await fetch(`${BASE}${path}`, { ...init, headers });
  if (resp.status === 401) {
    useAuthStore.getState().handle401();
  }
  return resp;
}

function buildListQuery(p: ListTasksParams): string {
  const params = new URLSearchParams();
  for (const s of p.status ?? []) params.append('status', s);
  for (const t of p.task_type ?? []) params.append('task_type', t);
  if (p.workflow_id) params.set('workflow_id', p.workflow_id);
  if (p.q) params.set('q', p.q);
  if (p.limit !== undefined) params.set('limit', String(p.limit));
  if (p.offset !== undefined) params.set('offset', String(p.offset));
  const qs = params.toString();
  return qs ? `?${qs}` : '';
}

// ---------------------------------------------------------------------------
// Public API.
// ---------------------------------------------------------------------------

export async function listTasks(
  params: ListTasksParams = {},
): Promise<TaskListResponse> {
  const resp = await authedFetch(`/api/v1/tasks${buildListQuery(params)}`);
  if (!resp.ok) {
    throw new Error(`listTasks failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as TaskListResponse;
}

export async function getTaskSummary(params: { task_type?: TaskType[] } = {}): Promise<TaskSummary> {
  const query = new URLSearchParams();
  for (const type of params.task_type ?? []) query.append('task_type', type);
  const suffix = query.toString() ? `?${query.toString()}` : '';
  const resp = await authedFetch(`/api/v1/tasks/summary${suffix}`);
  if (!resp.ok) {
    throw new Error(`getTaskSummary failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as TaskSummary;
}

export async function getTask(id: string): Promise<Task> {
  // Use the codegenned client for the single-task GET since the schema
  // already has it — keeps the existing 401 middleware in play.
  const { data, error } = await apiClient.GET(
    '/api/v1/tasks/{task_id}',
    { params: { path: { task_id: id } } },
  );
  if (error) throw error;
  return data as unknown as Task;
}

export async function cancelTask(
  id: string,
  mode: CancelMode = 'soft',
): Promise<{ status: string }> {
  const resp = await authedFetch(`/api/v1/tasks/${id}/cancel`, {
    method: 'POST',
    body: JSON.stringify({ mode }),
  });
  if (!resp.ok) {
    throw new Error(`cancelTask failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string };
}

export async function resumeTask(id: string): Promise<{ status: string; task_id: string }> {
  const resp = await authedFetch(`/api/v1/tasks/${id}/resume`, {
    method: 'POST',
  });
  if (!resp.ok) {
    throw new Error(`resumeTask failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string; task_id: string };
}

export async function createScheduledRun(
  body: ScheduledRunCreateBody,
): Promise<ScheduledRunResponse> {
  const resp = await authedFetch('/api/v1/tasks/scheduled-runs', {
    method: 'POST',
    body: JSON.stringify(body),
  });
  if (!resp.ok) {
    throw new Error(`createScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as ScheduledRunResponse;
}

export async function getScheduledRun(id: string): Promise<ScheduledRunResponse> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}`);
  if (!resp.ok) {
    throw new Error(`getScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as ScheduledRunResponse;
}

export async function patchScheduledRun(
  id: string,
  body: Partial<ScheduledRunCreateBody>,
): Promise<ScheduledRunResponse> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(body),
  });
  if (!resp.ok) {
    throw new Error(`patchScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as ScheduledRunResponse;
}

export async function pauseScheduledRun(id: string): Promise<{ status: string; schedule: ScheduledRunConfig }> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}/pause`, {
    method: 'POST',
  });
  if (!resp.ok) {
    throw new Error(`pauseScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string; schedule: ScheduledRunConfig };
}

export async function resumeScheduledRun(id: string): Promise<{ status: string; schedule: ScheduledRunConfig }> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}/resume`, {
    method: 'POST',
  });
  if (!resp.ok) {
    throw new Error(`resumeScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string; schedule: ScheduledRunConfig };
}

export async function runScheduledNow(
  id: string,
): Promise<{ status: string; execution: ScheduledRunExecution }> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}/run-now`, {
    method: 'POST',
  });
  if (!resp.ok) {
    throw new Error(`runScheduledNow failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string; execution: ScheduledRunExecution };
}

export async function deleteScheduledRun(id: string): Promise<{ status: string }> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}`, {
    method: 'DELETE',
  });
  if (!resp.ok) {
    throw new Error(`deleteScheduledRun failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string };
}

export async function listScheduledRunExecutions(
  id: string,
  params: { limit?: number; offset?: number } = {},
): Promise<ScheduledRunExecutionsResponse> {
  const qs = new URLSearchParams();
  if (params.limit !== undefined) qs.set('limit', String(params.limit));
  if (params.offset !== undefined) qs.set('offset', String(params.offset));
  const query = qs.toString();
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${id}/executions${query ? `?${query}` : ''}`);
  if (!resp.ok) {
    throw new Error(`listScheduledRunExecutions failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as ScheduledRunExecutionsResponse;
}

export async function cancelScheduledExecution(
  taskId: string,
  executionId: string,
): Promise<{ status: string }> {
  const resp = await authedFetch(`/api/v1/tasks/scheduled-runs/${taskId}/executions/${executionId}/cancel`, {
    method: 'POST',
  });
  if (!resp.ok) {
    throw new Error(`cancelScheduledExecution failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { status: string };
}

export async function getTaskEvents(
  id: string,
  params: {
    after_seq?: number;
    before_seq?: number;
    event_type?: TaskEventType[];
    limit?: number;
    from?: string;
    to?: string;
    order?: 'asc' | 'desc';
  } = {},
): Promise<TaskEventsResponse> {
  const qs = new URLSearchParams();
  if (params.after_seq !== undefined) qs.set('after_seq', String(params.after_seq));
  if (params.before_seq !== undefined) qs.set('before_seq', String(params.before_seq));
  for (const t of params.event_type ?? []) qs.append('event_type', t);
  if (params.limit !== undefined) qs.set('limit', String(params.limit));
  if (params.from) qs.set('from', params.from);
  if (params.to) qs.set('to', params.to);
  if (params.order) qs.set('order', params.order);
  const query = qs.toString();
  const resp = await authedFetch(`/api/v1/tasks/${id}/events${query ? `?${query}` : ''}`);
  if (!resp.ok) {
    throw new Error(`getTaskEvents failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as TaskEventsResponse;
}

/** Where the aggregated results table is written. v1: a durable /data VFS path.
 *  The `type` is the destination kind (future: cloud sheets) — see the backend
 *  BatchOutputSink abstraction. Omit `output` to keep results only in the task's
 *  downloadable copy. */
export interface BatchOutputSpec {
  type: 'vfs_data';
  path: string;
  /** The sheet to write into when `path` is an Excel file (.xlsx/.xls). */
  sheet_name?: string;
}

/**
 * One column of the batch output table. The output table is EXACTLY these
 * columns, in array order (left-to-right). `index`/`status`/`error`/
 * `execution_time` are fixed per-row metadata columns; `field` pulls a value
 * from a node's output (`node`.`field`), with an optional `default` substituted
 * when the run produced no value. `default` is omitted from the wire when blank.
 */
export type BatchOutputColumn =
  | { kind: 'index'; name: string }
  | { kind: 'status'; name: string }
  | { kind: 'execution_time'; name: string }
  | { kind: 'error'; name: string }
  | { kind: 'field'; name: string; node: string; field: string; default?: string };

export interface SubmitBatchBody {
  data_source: unknown;
  column_mapping: Record<string, string>;
  output?: BatchOutputSpec | null;
  /** How many rows run in parallel (thread pool, clamped 1..16 server-side). */
  concurrency?: number;
  /** The exact, ordered output-table columns. Omitted → server default shape. */
  output_columns?: BatchOutputColumn[];
}

export async function submitBatch(
  wfId: string,
  body: SubmitBatchBody,
): Promise<{ task_id: string }> {
  const resp = await authedFetch(`/api/v1/workflows/${wfId}/batch`, {
    method: 'POST',
    body: JSON.stringify(body),
  });
  if (!resp.ok) {
    throw new Error(`submitBatch failed: ${resp.status} ${resp.statusText}`);
  }
  return (await resp.json()) as { task_id: string };
}
