# -*- coding: utf-8 -*-
"""SubAgentNode — run a bounded tool-using agent as a workflow node."""
from __future__ import annotations

import asyncio
import jsonschema
from copy import deepcopy

from ..register import node_registry
from ..utils import safe_call_with_args
from .base import BaseNode
from .prompt import PromptNode


@node_registry.register()
class SubAgentNode(BaseNode):
    """SubAgentNode — delegate a bounded, tool-using subtask inside a workflow."""

    CONFIG_SCHEMA = {
        "type": "object",
        "required": ["task_template", "model_name"],
        "properties": {
            "retry": {"type": "integer", "minimum": 0, "maximum": 10, "default": 0,
                      "description": "Extra attempts per failed model request (0 disables retries). Retry transient network, rate-limit, server and empty-response errors with exponential backoff; never replay successful tools."},
            "task_template": {
                "type": "string",
                "description": (
                    "Delegated task template. Supports {{field}} interpolation."
                ),
            },
            "model_name": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "The exact models key returned by "
                    "flowork-cli config get --scope model_api. Fetch it in the current build "
                    "turn and copy one enabled key verbatim; never use the chat "
                    "Agent model, a provider model id, or a guessed name."
                ),
            },
            "skills": {
                "type": "array", "default": [], "uniqueItems": True,
                "description": "Installed Skill references discovered through flowork-cli skill; use the latest published content at the start of each execution.",
                "items": {
                    "type": "object", "additionalProperties": False,
                    "required": ["id", "name"],
                    "properties": {
                        "id": {"type": "string", "minLength": 1},
                        "name": {"type": "string", "minLength": 1},
                    },
                },
            },
            "mcp_servers": {
                "type": "array", "default": [], "uniqueItems": True,
                "description": "Installed MCP references discovered through flowork-cli mcp; credentials are resolved by the host.",
                "items": {
                    "type": "object", "additionalProperties": False,
                    "required": ["id", "name"],
                    "properties": {
                        "id": {"type": "string", "minLength": 1},
                        "name": {"type": "string", "minLength": 1},
                    },
                },
            },
            "max_iterations": {
                "type": "integer",
                "minimum": 1,
                "description": "Maximum tool-use iterations.",
            },
        },
        "additionalProperties": False,
    }

    AGENT_SPEC = {
        "summary": "Run a bounded tool-using worker and return structured output.",
        "when_to_use": (
            "Subtasks that need shell/file operations, web search, image inspection, or several intermediate steps before producing output. Tools: bash, web_search, read_images; set_output submits the result."
        ),
        "when_not_to_use": (
            "Use PromptNode for a single LLM call with no tool use. Use CodeNode for deterministic logic."
        ),
        "constraints": [
            "The worker must call set_output with the declared business fields to finish successfully; plain prose is not the result. Do not ask it to return only a final text answer.",
            "output_fields must include __traces__ with type array. This reserved field is generated by the runtime as ChatML messages; do not ask the model to produce it.",
            "Mandatory model-discovery gate: in the current build turn, call flowork-cli config get --scope model_api before writing any SubAgentNode, then copy one enabled models key exactly into model_name.",
            "Never use the chat Agent's runtime model id, a provider model id, or a guessed/familiar model name. If global config returns no model, do not create this node; ask the user to configure an API model first.",
        ],
        "config_guide": {
            "skills": "Optional list of {id,name} installed Skill references from flowork-cli skill list/get. No revision field: each execution resolves latest published content once. Do not freeze discovered version numbers, hashes, or Skill paths in task_template; read the runtime-provided Skill instructions.",
            "mcp_servers": "Optional list of {id,name} installed MCP references from flowork-cli mcp list/get/tools. Only selected servers supply tools; never include credentials.",
            "model_name": (
                "Exact enabled key from flowork-cli config get --scope model_api. Fetch it in "
                "this build turn and copy it verbatim; never guess or substitute "
                "the Agent runtime model."
            ),
            "task_template": (
                "Readable task brief for the worker. Include what to inspect, what to do, and what to return."
            ),
        },
        "examples": [
            {
                "scenario": "Read a file and summarize it",
                "node_dict": {
                    "node_id": "node_4",
                    "node_name": "file_summarizer",
                    "node_type": "SubAgentNode",
                    "node_description": "Read a file with tools and produce a concise summary",
                    "input_fields": {
                        "file_path": {"type": "string", "value": "", "reference": "__start__.file_path"}
                    },
                    "output_fields": {
                        "summary": {"type": "string", "description": "Concise file summary"},
                        "__traces__": {"type": "array", "description": "Runtime execution messages (ChatML)"}
                    },
                    "node_config": {
                        "task_template": "# Task\nRead {{file_path}} and summarize its key points.\n\n# Instructions\nUse file tools to read the file, identify the important information, and produce a concise summary.\n\n# Output\nCall set_output with the summary field; do not supply __traces__, which the runtime records.",
                        "model_name": "<manual-api-name>",
                        "max_iterations": 10,
                    },
                    "children": ["node_5"],
                    "__attributes__": {"x": 300, "y": 0},
                },
            }
        ],
        "display": {
            "name": {"en": "SubAgentNode", "zh": "子智能体节点"},
            "description": {"en": "Run a tool-using sub-agent", "zh": "运行可调用工具的子智能体"},
            "icon": "agent",
            "category": {"en": "AI Inference", "zh": "AI 推理"},
        },
    }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @staticmethod
    @safe_call_with_args(prefix="[SubAgentNode Check]: ")
    def check(node_dict: dict) -> bool:
        jsonschema.validate(instance=node_dict, schema=BaseNode.GENERAL_NODE_SCHEMA)
        specific_schema = deepcopy(BaseNode.GENERAL_NODE_SCHEMA)
        specific_schema["properties"]["node_config"] = SubAgentNode.CONFIG_SCHEMA
        jsonschema.validate(instance=node_dict, schema=specific_schema)
        jsonschema.validate(
            instance=node_dict,
            schema={
                "type": "object",
                "properties": {
                    "node_type": {"const": "SubAgentNode"},
                    "children": {"type": "array", "maxItems": 1},
                },
            },
        )
        output_fields = node_dict.get("output_fields") or {}
        assert "__traces__" in output_fields, (
            "SubAgentNode requires the fixed output field '__traces__'."
        )
        assert output_fields["__traces__"].get("type") == "array", (
            "SubAgentNode output_fields.__traces__ type must be 'array'."
        )
        for collection, key in (("skills", "id"), ("mcp_servers", "id")):
            refs = node_dict["node_config"].get(collection, [])
            assert len({ref[key] for ref in refs}) == len(refs), f"Duplicate {collection} resource ID."

    @staticmethod
    def _agent_cfg(model_name: str, extra: dict | None) -> dict:
        """Build the model descriptor for this in-sandbox worker.

        Workflow execution injects a short-lived Runtime Model Broker
        capability, not the provider credential. Unlike the host Chat Runtime,
        this worker constructs its model client directly inside the workflow
        sandbox, so the broker URL and capability must reach that constructor.
        Passing the entry through ``merge_agent_settings_override`` is wrong at
        this boundary: that helper deliberately strips connection fields for a
        later Chat-Runtime dispatch step which does not exist here.
        """
        injected = (extra or {}).get("llm_credentials") or {}
        if model_name in injected:
            entry = injected[model_name]
            provider = str(entry.get("provider") or "").strip()
            provider_model = str(entry.get("model_name") or "").strip()
            broker_url = str(entry.get("api_url") or "").strip()
            capability = str(entry.get("api_key") or "").strip()
            if not provider or not provider_model or not broker_url or not capability:
                raise RuntimeError(
                    f"Injected Runtime Model Broker configuration for "
                    f"'{model_name}' is incomplete."
                )
            agent_cfg = {
                "model": f"{provider}:{provider_model}",
                "base_url": broker_url,
                # This is a short-lived broker capability, never the provider
                # API key. The broker re-authorizes every upstream request.
                "api_key": capability,
            }
            if entry.get("model_context_tokens"):
                agent_cfg["model_context_tokens"] = int(
                    entry["model_context_tokens"]
                )
            if entry.get("timeout"):
                agent_cfg["timeout"] = int(entry["timeout"])
            return agent_cfg
        raise RuntimeError(
            "Workflow model is unavailable; select your enabled manually added API. "
            "Platform defaults and account connections are not supported."
        )

    @staticmethod
    def _system_prompt() -> str:
        return (
            "You are a bounded workflow sub-agent. Complete only the delegated "
            "task from the user message. Use tools when they are necessary to "
            "inspect or modify workspace files, and avoid unrelated exploration. "
            "Use bash for file reading, editing and scripts; web_search returns "
            "source links and snippets, not full pages; read_images provides "
            "image pixels to your vision capability. "
            "When the task is complete, call set_output exactly once with the "
            "requested structured fields."
        )

    async def _call_async(self, inputs: dict, extra: dict | None) -> dict:
        from vibecanvas_api.agents.tool_runtime import AgentContext
        from vibecanvas_api.services.workflow_subagent import workflow_chat_model
        from vibecanvas_api.agents.tools.subagent.core import run_bounded_agent
        from vibecanvas_api.agents.tools.subagent.toolset import build_agent_subagent_tools

        from vibecanvas_api.agents.tools.subagent.resources import (
            resolved_node_resources, resource_tools, skill_instructions,
        )

        cfg = self.node_config
        resource_snapshot = resolved_node_resources(self.node_id, cfg, extra)
        task, _images, _videos, _audios = PromptNode.format_prompt_template(
            cfg["task_template"], inputs, unpack_multimodal=False
        )
        agent_cfg = self._agent_cfg(cfg["model_name"], extra)
        agent_cfg["max_retries"] = 0
        ctx = AgentContext(
            wf_id=(extra or {}).get("run_id") or "",
            run_id=(extra or {}).get("run_id") or "",
            agent_cfg=agent_cfg,
            stop_event=(extra or {}).get("stop_event"),
        )
        from vibecanvas_api.agents.tools.subagent.audit import ResourceAudit
        audit = ResourceAudit(resource_snapshot)
        if extra is not None:
            extra['_subagent_resource_audit'] = audit.payload
        async with (
            workflow_chat_model(agent_cfg) as model,
            resource_tools(resource_snapshot) as selected_tools,
        ):
            result = await run_bounded_agent(
                model=model,
                tools=build_agent_subagent_tools(working_dir=(extra or {}).get("run_dir")) + selected_tools,
                system_prompt=self._system_prompt() + "\n\n" + skill_instructions(resource_snapshot),
                user_input=task,
                output_fields={key: value for key, value in self.output_fields.items() if key != "__traces__"},
                max_iterations=int(cfg.get("max_iterations") or 25),
                retry=cfg.get("retry", 0),
                context=ctx,
                checkpointer=None,
                thread_id=None,
                on_trace=audit.record,
            )
        if extra is not None:
            extra["_subagent_traces"] = result.messages
        if result.status != "done":
            raise RuntimeError(result.error or f"SubAgentNode ended with status {result.status}")
        return {**result.output, "__traces__": result.messages}

    @safe_call_with_args(prefix="[SubAgentNode Call]: ")
    def __call__(self, inputs: dict, previous_outputs: dict, extra: dict = None) -> dict:
        stop_event = (extra or {}).get("stop_event")
        if stop_event is not None and stop_event.is_set():
            raise RuntimeError("SubAgentNode cancelled before agent call.")
        # ``safe_call_with_args`` owns the standard node-result envelope. Return
        # only the declared fields here, exactly like PromptNode/CodeNode;
        # returning another envelope would persist
        # ``{status, output: {analysis_summary: ...}}`` as the node output and
        # break downstream references such as ``worker.analysis_summary``.
        return asyncio.run(self._call_async(inputs, extra if extra is not None else {}))

    @safe_call_with_args(prefix="[SubAgentNode Call]: ")
    async def call_async(self, inputs: dict, previous_outputs: dict, extra: dict = None) -> dict:
        stop_event = (extra or {}).get("stop_event")
        if stop_event is not None and stop_event.is_set():
            raise RuntimeError("SubAgentNode cancelled before agent call.")
        return await self._call_async(inputs, extra if extra is not None else {})
